import {StyleSheet} from 'react-native';

export default StyleSheet.create({
  wrapper: {
    paddingVertical: 28,
    paddingHorizontal: 12,
    backgroundColor: 'white',
  },
  textHeaderOne: {
    fontSize: 16,
    color: '#A0A3BD',
    fontWeight: '600',
  },
  textJumbo: {
    color: '#5F2EEA',
    fontSize: 46,
    fontWeight: '700',
  },
  imageJumboSec: {
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 52,
  },
  imageJumbo: {
    width: 300,
    height: 300,
  },
  showingHeader: {
    marginTop: 30,
    paddingVertical: 12,
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  textShowing: {
    fontSize: 20,
    fontWeight: '600',
    color: '#14142B',
  },
  textViewAll: {
    color: '#5F2EEA',
    fontSize: 16,
    fontWeight: '600',
  },
  wrapperShowing: {
    flexDirection: 'row',
    paddingVertical: 12,
  },
  cardShowing: {
    margin: 10,
    borderRadius: 6,
    justifyContent: 'center',
    alignItems: 'center',
    padding: 10,
    width: 154,
    height: 217,
    backgroundColor: 'white',
  },
  cardUpComing: {
    margin: 10,
    borderRadius: 6,
    justifyContent: 'center',
    alignItems: 'center',
    padding: 10,
    width: 154,
    height: 317,
    backgroundColor: 'white',
  },
  imageShowing: {
    borderRadius: 6,
    width: 122,
    height: 185,
  },
  monthList: {
    marginHorizontal: 6,
    backgroundColor: 'white',
    width: 100,
    height: 32,
    borderRadius: 6,
    alignItems: 'center',
    justifyContent: 'center',
    color: '#5F2EEA',
    borderWidth: 1,
    borderColor: '#5F2EEA',
  },
  textMonth: {
    color: '#5F2EEA',
    fontWeight: '600',
    fontSize: 16,
  },
  titleUpComing: {
    color: '#14142B',
    marginTop: 8,
    fontSize: 18,
  },
  genre: {
    fontSize: 12,
  },
  btnDetail: {
    width: '100%',
    height: 25,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 4,
    marginTop: 18,
    color: '#5F2EEA',
    borderWidth: 1,
    borderColor: '#5F2EEA',
  },
  textDetail: {
    color: '#5F2EEA',
    fontSize: 13,
  },
  subsHeader: {},
  inputText: {
    width: '100%',
    paddingLeft: 12,
    marginTop: 18,
    backgroundColor: 'white',
    borderRadius: 8,
  },
  btnJoin: {
    width: '100%',
    marginTop: 18,
    backgroundColor: '#5F2EEA',
    height: 46,
    borderRadius: 8,
    justifyContent: 'center',
    alignItems: 'center',
  },
  textjoin: {
    color: 'white',
    fontSize: 16,
  },
  descJoin: {
    marginTop: 22,
    marginHorizontal: 'auto',
    width: '75%',
    textAlign: 'center',
    fontSize: 16,
  },
});
